name: CI

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  continous-integration:
    name: CI
    runs-on: [ubuntu-latest]
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PERSONAL_GITHUB_TOKEN: ${{secrets.PERSONAL_GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v1.2.0
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run bootstrap -- --ci
      - run: npm run lint
      - run: npm run test:coverage
      # - name: Fix code coverage paths
      #   # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747/5
      #   run: |
      #     REPO_NAME="$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)"
      #     sed -i "s/\/home\/runner\/work\/$REPO_NAME\/$REPO_NAME\//\/github\/workspace\//g" coverage/lcov.info
      #     sed -i "s/\/home\/runner\/work\/$REPO_NAME\/$REPO_NAME\//\/github\/workspace\//g" test-report.xml
      # - name: Analyze on SonarCloud
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
