name: develop CI/CD
on:
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Relase
    runs-on: [ubuntu-latest]
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PERSONAL_GITHUB_TOKEN: ${{secrets.PERSONAL_GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v1.2.0
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - uses: ./.github/actions/release-monorepo
